### ISSUE TITLE
Metal Gear Solid V Translation Tool

### ISSUE THREAD

**Issue by romhackingvn** [Atvaark/FoxEngine.TranslationTool#6] opened 2016-01-21 03:47 UTC
I want to send you a big thanks! I complete translated Metal Gear Solid V GZ on PC version. I got you on my staff, special thanks! Could I have a request? Please take and you PS3 version, I try with your tool in PS3 and it isn't working, maybe bigendian, I am not good about code, please help me. Font tool working normal, just lang tool and subp tool not working on PS3 version. Thanks! 

Exmaple file between PC and PS3 ver:
https://www.dropbox.com/s/hgv96jy31ecv0o0/Metal%20Gear%20Solid%20V%20GZ%20Research.rar?dl=0

**Comment by Atvaark** [comment] 2016-02-15 06:48
Duplicate of #3.

**Closed as completed by Atvaark** 2016-02-15 06:48 UTC
Labels: duplicate
